apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  labels:
    app: account
  namespace: production
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      imagePullSecrets:
        - name: neodsc-secret
      containers:
        - name: account
          image: 'registry-vpc.cn-beijing.aliyuncs.com/xxx/account:IMAGE_TAG'
          imagePullPolicy: Always
          ports:
            - containerPort: 8430
              protocol: TCP
          env:
            - name: APP_OPTS
              value: "--spring.profiles.active=prod"